language: node_js
node_js:
- '9'
deploy:
  provider: script
  script: bin/deploy.sh
  on:
    branch: dev
env:
  global:
  - secure: Uc0eYZEqqM0KMU0oskwGBv28dvgVRHsF95NfOB3h4yxui94Uc/0yZyv1QDYRtNxY7HPNs9dkD1egtXdthZISsLidYt4zF9q5XpdSIp/00cPyCsVgyOROT5C/DNXwn90AXWdYojea8J/8ZnMu6bcFGX7/LP2HxeqYfgrTppiYj0nSBx96z69DiGBpJicfhUZvSd36noZMzPv+IDYeDGCYtTJukM70XcR6/VBvGlz5Dw8J1icoswcStcOuZu3fqcs4yusx3Otjg5svirnIf2rNrmfKwWl/U9TjN39/Ha4Aab1yuef32aLzTzgzEBcc1i/ffIDCmDc6JJH/26zWtNAvH+k9JtrssSAsqT17ydn4qFtbe/93oFXdaMOTC1JLHdsQRQ1gPhpp6Fmj5zeUvD7GS4eaOgjLE1sAL8I21wuOYUBuHsY8JleabvFGEOYJ68272jmeoSsyVOGo1DEQR6dqIwiP+5HOYu2nBhGMRpsraJXQjurc5szgVF8tgDy1ArkpSQgSnrlZSYM3I/Aq8Ds7P0OljhODsL0FcU4rFSL6I5DeZFr378uY4cIItTbxvY7eruXjKXIIrE5/bbTYvQmj1p3xkLZkqLvNpOsYPAGnymHxqyKd7mrCGLfT6XjMJjyiBxfbb7zlLyMT/GZE3bMJOQwX2aEB4tibpM2tK/942dE=
  - secure: SU8TwVJxwggXfvBZE0/qcdwVT30Po3zVQlp7nsykxZAvBGd4rJWyyMd50pklQ/fD1mdy4OfarLW/dDHc5JJfUP6xXyP7lBk6VhvGQu2HokXZ/pn9c1v7fSWl3AUNFPCL2t80a1FqW/j6GgBXy4/7Cx8mEr9SfPNB3zXNFg5w4tfZ+zONPRATYl18nrxUpAsRvIcZ23MX5exrfwdMnUuZVzZgwxllibyvYG3BbFC4RgKD7Zsk6tIQEy8ZTnAVEfHg3c2ZTHBfgEBHyPz+x001WFGMobAly3kG5bj6g/+j5c9McZQm1vFRrDC+a1Chlmd9CRjly87wzth2REel+oIzJKRVWCSGZ5ZsYZFl2IOqTAqEGRy5QWWoK7D2fnR1j7FN1ldZVnht6YdPxUpwqAod/QO6+spbWDAKpCs47YIYLbmwnKpQTBaIpfp8hevyjxGLw8/wxUD0BJBhx8yc2LRh9InmVaQr/fT0/6Biea3VmmrUjxC+m5n+8UwzKnLb2ELLmtxuMhFbgS63WUTyf8NSlIT9OzNSl74tIPC9HnrMDGhjjs7euZBrlzqm8TSrONadNgJQw3xaxZHALQddCb17esnBBWTNpn2UFbfjREO4CNTQb9Oh1uorJ7U1UqvLBYmVvbe2nKNITf1//nXSE/8lGep/r3eP+4Srb9ylro52neM=
